resolver: nightly-2022-09-23
packages:
- .

extra-deps:
#
# there was actually no immediate reason to depend on the latest versions of
# these libraries other than to show the way you add specific versions to your
# Stack resolver if you need something newer than what is in the snaphot above.
#

- core-data-0.3.6.0
- core-program-0.5.2.0
- core-text-0.3.8.0
- core-telemetry-0.2.6.0

#
# bump aeson dependency for security reasons
#
